# Generated by Django 3.2.16 on 2024-04-11 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('birthday', '0004_congratulation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20, verbose_name='Тег')),
            ],
        ),
        migrations.AlterModelOptions(
            name='congratulation',
            options={'ordering': ('created_at',), 'verbose_name': 'поздравления', 'verbose_name_plural': 'Поздравление'},
        ),
        migrations.AlterField(
            model_name='congratulation',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор поздравления'),
        ),
        migrations.AlterField(
            model_name='congratulation',
            name='birthday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='congratulations', to='birthday.birthday', verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='congratulation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата поздрвления'),
        ),
        migrations.AddField(
            model_name='birthday',
            name='tag',
            field=models.ManyToManyField(blank=True, help_text='Удерживайте Ctrl для выбора нескольких вариантов', to='birthday.Tag', verbose_name='Теги'),
        ),
    ]
