# Generated by Django 3.2.16 on 2024-04-11 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0005_auto_20240411_0639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'теги', 'verbose_name_plural': 'Тег'},
        ),
        migrations.RenameField(
            model_name='birthday',
            old_name='tag',
            new_name='tags',
        ),
    ]
